List<Map<String, String>> allFonts = [
  {'font': 'Roboto', 'bgColor': '0xffFAD02E'},
  {'font': 'Poppins', 'bgColor': '0xff81C784'},
  {'font': 'Lato', 'bgColor': '0xff80CBC4'},
  {'font': 'Inter', 'bgColor': '0xffFF8A65'},
  {'font': 'Oswald', 'bgColor': '0xff9575CD'},
  {'font': 'Raleway', 'bgColor': '0xffFFD54F'},
  {'font': 'Montserrat', 'bgColor': '0xffFF7043'},
  {'font': 'Merriweather', 'bgColor': '0xff4DB6AC'},
  {'font': 'Kanit', 'bgColor': '0xff90A4AE'},
  {'font': 'Lora', 'bgColor': '0xffAED581'},
  {'font': 'Teko', 'bgColor': '0xffFFD180'},
  {'font': 'Mulish', 'bgColor': '0xff4FC3F7'},
  {'font': 'Barlow', 'bgColor': '0xffE57373'},
  {'font': 'Quicksand', 'bgColor': '0xffB39DDB'},
  {'font': 'Inconsolata', 'bgColor': '0xff81D4FA'},
  {'font': 'Karla', 'bgColor': '0xffEF9A9A'},
  {'font': 'Dosis', 'bgColor': '0xffDCE775'},
  {'font': 'Dokdo', 'bgColor': '0xff9CCC65'},
  {'font': 'Caveat', 'bgColor': '0xffFFAB91'},
  {'font': 'Gaegu', 'bgColor': '0xffFFCC80'},
];
